In [5]:
import numpy as np
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

In [13]:

data = pd.read_csv("data/frontiers.csv")
testFrontier = data.loc[data.Frontier == "test"]
x = testFrontier["Restoration (Ha-yr)"]
y = testFrontier["Employment (m3 eucalyptus)"]
z = testFrontier["Income (USD)"]

In [9]:
fig = plt.figure()

,Frontier,SolutionIndex,Restoration (Ha-yr),Employment (m3 eucalyptus),Income (USD)
0,test,0,50540.2395,259677.094,923684.6805
1,test,1,50604.4655,278147.729,554947.5834
2,test,10,50134.8495,336014.098,392940.6460
3,test,11,45297.8110,289317.164,1349990.0000
4,test,12,49921.5195,335133.183,708935.6983
5,test,13,49361.9310,315813.629,1003866.6420
6,test,14,48881.0100,334637.597,992423.3023
7,test,15,47730.6100,307481.343,1273318.7930
8,test,16,47046.7440,251453.071,1620229.9570
9,test,17,45730.1725,272361.188,1620581.7920
10,test,20,43588.2315,254373.352,1878475.0710
11,test,21,45081.1450,272494.358,1870626.6680
12,test,22,44792.8710,290523.754,1779675.4700
13,test,23,43796.2385,326535.324,1516428.7380
14,test,24,42538.0980,309731.617,1797050.2040
15,test,25,49343.9220,354364.059,356243.1272
16,test,26,48454.2925,354883.196,623913.9505
17,test,27,48598.3905,353146.426,877381.3734
18,test,28,46161.9540,344791.125,1245260.9930
19,test,29,44175.3325,231122.577,2136818.5510
20,test,3,50070.7000,297288.242,756158.4053
21,test,30,42895.4305,250624.307,2128730.2870
22,test,31,44764.3980,344558.552,1495303.3400
23,test,32,43004.7880,328009.495,1766603.4810
24,test,33,41646.8735,272622.889,2126426.5850
25,test,34,42207.8355,290665.156,2047973.2990
26,test,35,39344.4080,308939.333,2051380.1910
27,test,36,37378.3110,327164.537,2048382.0260
28,test,37,39059.7835,251229.395,2385786.9010
29,test,38,38077.5520,291556.484,2305974.8760
30,test,39,40975.6045,346108.261,1745468.6730
31,test,4,50339.4870,317925.718,457663.5162
32,test,40,38937.2375,346049.744,1997039.4190
33,test,41,37541.6020,309583.387,2301413.3430
34,test,42,36182.7505,327589.860,2298436.1590
35,test,43,35312.3270,269701.241,2558966.1530
36,test,44,34485.6780,287711.744,2556022.4570
37,test,45,31520.7335,236874.525,2809604.9920
38,test,5,50378.5185,245705.149,1186822.2440
39,test,6,49988.3010,277738.716,1095621.1390
40,test,7,49685.9430,315961.111,738224.7622
41,test,8,49823.0790,295882.470,1022863.0030